import { EventList } from '~/types/schemas/event-list';

export const defaultEventListTheme: EventList = {
  title: 'Event list title',
  events_activate: [
    {
      value: '10',
      label: 'Follow',
    },
    {
      value: '20',
      label: 'Bits',
    },
    {
      value: '30',
      label: 'Subscribe',
    },
    {
      value: '31',
      label: 'Subscription Gift',
    },
    {
      value: '40',
      label: 'Raid',
    },
    {
      value: '50',
      label: 'Hype Train Begin',
    },
    {
      value: '52',
      label: 'Hype Train End',
    },
    {
      value: '60',
      label: 'Goal Begin',
    },
    {
      value: '61',
      label: 'Goal End',
    },
  ],
  alignment: 'right',
  events_spacing: 8,
  animation_in: 'fade-in-left',
  delete_event: true,
  duration_before_delete: 7000,
  events: {
    texts: {
      follow: {
        name: 'Follow',
        message: '**{{pseudo}}** follow the channel!',
      },
      cheer: {
        name: 'Bits',
        message: '**{{pseudo}}** donate **{{amount}}** bits!',
      },
      subscribe: {
        name: 'Subscribe',
        message: '**{{pseudo}}** subscribe the channel with **{{tier}}**!',
      },
      subscription_gift: {
        name: 'Subscription Gift',
        message: '**{{pseudo}}** gift **{{amount}}** subscription!',
      },
      raid: {
        name: 'Raid',
        message: '**{{pseudo}}** raid the channel with **{{amount}}** viewers!',
      },
      hype_train_begin: {
        name: 'Hype Train Begin',
        message: 'Hype train begin with **{{level}}** level!',
      },
      hype_train_end: {
        name: 'Hype Train End',
        message: 'Hype train end with **{{level}}** level!',
      },
      goal_begin: {
        name: 'Goal Begin',
        message: 'Goal begin with **{{amount}} {{type}}**!',
      },
      goal_end: {
        name: 'Goal End',
        message: 'Goal end with **{{amount}} {{type}}**!',
      },
    },
    modify_all: true,
    styles: {
      all: {
        container: {
          full_width: true,
          background: '#ffffff',
          border: {
            top: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 8,
            left: 0,
          },
          padding: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
        name: {
          hide: false,
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '600',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 0,
            top_right: 0,
            bottom_right: 0,
            bottom_left: 0,
          },
        },
        message: {
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '400',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          accent: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '700',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
      },
      follow: {
        container: {
          full_width: true,
          background: '#ffffff',
          border: {
            top: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 8,
            left: 0,
          },
          padding: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
        name: {
          hide: false,
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '600',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 0,
            top_right: 0,
            bottom_right: 0,
            bottom_left: 0,
          },
        },
        message: {
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '400',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          accent: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '700',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
      },
      cheer: {
        container: {
          full_width: true,
          background: '#ffffff',
          border: {
            top: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 8,
            left: 0,
          },
          padding: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
        name: {
          hide: false,
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '600',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 0,
            top_right: 0,
            bottom_right: 0,
            bottom_left: 0,
          },
        },
        message: {
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '400',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          accent: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '700',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
      },
      subscribe: {
        container: {
          full_width: true,
          background: '#ffffff',
          border: {
            top: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 8,
            left: 0,
          },
          padding: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
        name: {
          hide: false,
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '600',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 0,
            top_right: 0,
            bottom_right: 0,
            bottom_left: 0,
          },
        },
        message: {
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '400',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          accent: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '700',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
      },
      subscription_gift: {
        container: {
          full_width: true,
          background: '#ffffff',
          border: {
            top: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 8,
            left: 0,
          },
          padding: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
        name: {
          hide: false,
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '600',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 0,
            top_right: 0,
            bottom_right: 0,
            bottom_left: 0,
          },
        },
        message: {
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '400',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          accent: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '700',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
      },
      raid: {
        container: {
          full_width: true,
          background: '#ffffff',
          border: {
            top: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 8,
            left: 0,
          },
          padding: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
        name: {
          hide: false,
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '600',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 0,
            top_right: 0,
            bottom_right: 0,
            bottom_left: 0,
          },
        },
        message: {
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '400',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          accent: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '700',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
      },
      hype_train_begin: {
        container: {
          full_width: true,
          background: '#ffffff',
          border: {
            top: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 8,
            left: 0,
          },
          padding: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
        name: {
          hide: false,
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '600',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 0,
            top_right: 0,
            bottom_right: 0,
            bottom_left: 0,
          },
        },
        message: {
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '400',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          accent: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '700',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
      },
      hype_train_end: {
        container: {
          full_width: true,
          background: '#ffffff',
          border: {
            top: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 8,
            left: 0,
          },
          padding: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
        name: {
          hide: false,
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '600',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 0,
            top_right: 0,
            bottom_right: 0,
            bottom_left: 0,
          },
        },
        message: {
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '400',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          accent: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '700',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
      },
      goal_begin: {
        container: {
          full_width: true,
          background: '#ffffff',
          border: {
            top: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 8,
            left: 0,
          },
          padding: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
        name: {
          hide: false,
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '600',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 0,
            top_right: 0,
            bottom_right: 0,
            bottom_left: 0,
          },
        },
        message: {
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '400',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          accent: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '700',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
      },
      goal_end: {
        container: {
          full_width: true,
          background: '#ffffff',
          border: {
            top: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 8,
            left: 0,
          },
          padding: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
        name: {
          hide: false,
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '600',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 1,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 0,
            top_right: 0,
            bottom_right: 0,
            bottom_left: 0,
          },
        },
        message: {
          text_style: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '400',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          accent: {
            fontFamily: 'Rubik',
            fontSize: 16,
            fontWeight: '700',
            color: '#000000',
            textAlign: 'left',
            textDecoration: 'none',
            fontStyle: 'normal',
            letterSpacing: 0,
            lineHeight: 100,
            textShadow: {
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              shadowBlur: 0,
              shadowColor: '#000000',
            },
          },
          background: '#00000000',
          border: {
            top: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            right: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            bottom: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
            left: {
              color: '#000000',
              width: 0,
              style: 'solid',
            },
          },
          shadow: {
            shadowColor: '#000000',
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            shadowBlur: 0,
          },
          margin: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 12,
            right: 12,
            bottom: 12,
            left: 12,
          },
          radius: {
            top_left: 4,
            top_right: 4,
            bottom_right: 4,
            bottom_left: 4,
          },
        },
      },
    },
  },
  animation_out: 'fade-in-right',
};
